export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAIL='REGISTER_FAIL';
export const REGISTER_LOADING='REGISTER_LOADING';
export const AUTH_USER_SUCCESS='AUTH_USER_SUCCESS';
export const GET_USER_SUCCESS='GET_USER_SUCCESS';
